### ISSUE TITLE
업데이트 후 페이지를 건너 뜁니다

### ISSUE THREAD

**Issue by m00nlygreat** [nanikit/vim_comic_viewer#1]
1-3-5 순서로 페이지를 넘기는 경향이 있습니다
3에서 위 방향키를 누르면 2 페이지로 돌아가고요

제 경우에는 항상 그랬고 안 그러는 케이스가 있는진 잘 모르겠습니다

추가로 혹 키보드 단축키를 편집할 수 있게 만들어주실 수 있는지 궁금합니다 ...
제가 소스를 열어보았는데 몇개는 vim comic viewer의 단축키여서 수정이 어렵더라고요

한참 전 버전에서는 tampermonkey 스크립트의 단축키를 수정하고, 
vim comic viewer는 별도로 다운로드해서 키를 수정해 다른 곳에 호스팅함으로써 가능했는데. 
지난 버전에서는 왜인지 잘 안되더군요 ㅎㅎ;

오랫동안 잘 썼습니다. 감사합니다

**Comment by nanikit** [comment]
1-3-5 순서로 페이지가 넘어가는 건 [다른 분이 제보](https://greasyfork.org/en/scripts/418090-%ED%86%A0%EB%81%BC-%EB%B7%B0%EC%96%B4/discussions/209185)해주신 적이 있는데 제 환경에서 재현되지 않아 고치지 못했어요.

크롬 확장 프로그램이랑 다른 유저스크립트를 비활성화하고서도 재현되는지 확인 가능할까요? 게스트 모드 또는 새로운 프로필에서 테스트하면 될 것 같아요.

이 라이브러리를 실제로 쓰는 분이 있을 줄은 몰랐는데 빌드 툴을 별도로 만든 걸 쓰고 있어서 쓰시기 어려우셨을 것 같아요. 어떤 식으로 연동하셨는지 짐작이 안 돼서 알려주시면 참고가 될 것 같아요.

키 바인딩 설정 기능은 넣으려다가 슬슬 그만 개발해야겠다 생각해서 도움말만 넣고 말았는데 가능하면 UI를 넣지 않고 라이브러리 사용 코드에서 리스너로 뷰어를 조작하게 하는 선에서 그만하려고 생각했어요. 이게 힘들거나 만족이 안될 수 있는데 이 부분은 더 코멘트 부탁드려요.

**Comment by m00nlygreat** [comment]
아아 오해를 드렸습니다. vim comic viewer를 사용한 것은 아니구, 마나토끼 뷰어 Tampermonkey 스크립트를 쓰는데 어떤 단축키인가가 Tampermonkey 스크립트에서 제어가능한 것이 아니라 vim comic viewer를 수정해야 하길래 그냥 js 파일만 받아서 단축키에 해당하는 부분만 변경하고 다른 곳에 호스팅을 해서 Tampermonkey 스크립트의 import 부분에 넣어서 썼습니다. 저는 취미수준의 코딩을 하고 있기에 이 이상의 말씀은 알아듣지 못합니다 😂

저는 네비게이션에 주로 왼손을 쓰는데 단축키가 오른손 위주이길래 이걸 바꾸어서 쓰고 있었는데, 몇개월 전인가 vim comic viewer와 마나토끼 뷰어가 업데이트 되면서 쓸 수 없게 되었습니다. 이 단축키를 수정하는 방법에 대한 단서를 주시면 스스로 공부를 해보든지 하겠습니다

그래도 그간 정말 감사히 잘 썼습니다

**Comment by nanikit** [comment]
이전 스크립트 버전은 모두 [여기](https://greasyfork.org/ko/scripts/418090-%ED%86%A0%EB%81%BC-%EB%B7%B0%EC%96%B4/versions)에서 확인할 수 있어요. 이전 버전 URL을 사용하면 업데이트하지 않고 쓸 수 있을 것 같아요. 하지만 스크립트를 직접 수정한 시점에서 이미 자동 업데이트가 중단되었을 거라서 뭐가 문제였을진 의문이네요.

user.js 파일의 단축키를 수정하는 식으로 사용했다면 [이 부분](https://github.com/nanikit/vim_comic_viewer/blob/3d0e41ad2c23189b2fbba87e4022a7ad5a82dd22/vim_comic_viewer.user.js#L1166-L1188)을 수정하면 될 거예요. 제가 처음에 말한 방식은 본격적인 코딩이 필요해서 어려울 것 같아요.

얘기를 들어보니까 키 바인딩 설정 기능이 필요할 것 같긴 한데 이거 개발을 한동안 쉬려고 하고 있어서 어떨지 모르겠어요. 페이지 버그까지는 고치려고 하는데 재현이 안 돼서

> 크롬 확장 프로그램이랑 다른 유저스크립트를 비활성화하고서도 재현되는지 확인 가능할까요? 게스트 모드 또는 새로운 프로필에서 테스트하면 될 것 같아요.

이걸 알려주시면 도움이 될 것 같아요.

**Comment by m00nlygreat** [comment]
아이고 응답이 늦었습니다. 친절한 답변 감사합니다. 말씀드렸던 페이지 건너뛰는 문제는 더 이상 재현이 되지 않고 있습니다. 저도 원인을 모르겠습니다. 아무것도 안 했거든요..

키 바인딩은 일단 디폴트 키 바인딩에 새롭게 적응해서 저에게는 더 이상 문제가 아닙니다만. 이후에 다시 의욕이 생기시거든 그때 고려해주셔도 좋을것 같습니다! 그 때까지 또 잘 쓰고 있겠습니다... 감사합니다

**Comment by m00nlygreat** [comment]
제가 윈도우를 VHD 라는 걸로 구성을 해놔서, 이전 설정으로 돌아가서 다시 업데이트를 하고, 똑같은 증상을 겪고 또 정상화가 되었는데요. 이걸 테스트하려고 한 건 아니고 그냥 주기적으로 클린한 상태로 돌아가는 설정을 하고 있습니다.

특이한 점을 발견했는데. 페이지를 건너뛰는 버그가 있을 때는 뷰어를 ESC 눌러서 닫는 것도 함께 안되었습니다. 이후 똑같이 정상화(페이지 한장씩 잘 넘어감)되었을 때는 ESC 키도 작동하고요. 그냥 혹시 도움되실까 해서 제보 드려요.
